# Configuración para despliegue en Render
services:
  - type: web
    name: frontend-ferreteria
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    # Configuración para SPA (Single Page Application)
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    # Variables de entorno
    envVars:
      - key: SITE_URL
        value: https://tu-frontend-app.onrender.com